/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gusaja.praktikum_9;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String nHuruf, predikat;
    double tugas, uts, uas, ptugas, puts, puas, akhir;

    void hitung() {
        ptugas = 0.2 * tugas;
        puts = 0.35 * uts;
        puas = 0.45 * uas;
        akhir = ptugas + puts + puas;
    }

    String getNilHuruf() {
        if (akhir >= 85) {
            nHuruf = "A";
        } else if (akhir >= 70 && akhir < 85) {
            nHuruf = "B";
        } else if (akhir >= 65 && akhir < 70) {
            nHuruf = "C";
        } else {
            nHuruf = "D";
        }
        return nHuruf;
    }

    String getPredikat() {
        switch (nHuruf) {
            case "A":
                predikat = "Apik";
                break;
            case "B":
                predikat = "Bagus";
                break;
            case "C":
                predikat = "Jelek";
                break;
            case "D":
                predikat = "Dablek";
                break;
            default:
                predikat = "-";
        }
        return predikat;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim = new javax.swing.JTextField();
        ntugas = new javax.swing.JTextField();
        natugas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nauts = new javax.swing.JTextField();
        nuts = new javax.swing.JTextField();
        nauas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nuas = new javax.swing.JTextField();
        nakhir = new javax.swing.JTextField();
        npredikat = new javax.swing.JTextField();
        nhuruf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("NIM");

        jLabel3.setText("Nilai Tugas");

        jLabel4.setText("Nilai UTS");

        jLabel5.setText("Nilai UAS");

        jLabel6.setText("Nilai Akhir");

        jLabel7.setText("Nilai Huruf");

        jLabel8.setText("Predikat");

        ntugas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ntugasFocusLost(evt);
            }
        });

        natugas.setEditable(false);
        natugas.setBackground(new java.awt.Color(204, 204, 204));
        natugas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        natugas.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jLabel9.setText("20%");

        jLabel10.setText("35%");

        nauts.setEditable(false);
        nauts.setBackground(new java.awt.Color(204, 204, 204));

        nuts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nutsFocusLost(evt);
            }
        });

        nauas.setEditable(false);
        nauas.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("45%");

        nuas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nuasFocusLost(evt);
            }
        });

        nakhir.setEditable(false);
        nakhir.setBackground(new java.awt.Color(204, 204, 204));

        npredikat.setEditable(false);
        npredikat.setBackground(new java.awt.Color(204, 204, 204));

        nhuruf.setEditable(false);
        nhuruf.setBackground(new java.awt.Color(204, 204, 204));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Tugas", "UTS", "UAS", "Nilai Akhir", "Predikat", "Nilai Huruf"
            }
        ));
        jScrollPane2.setViewportView(table);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nama)
                                    .addComponent(nim)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nhuruf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                            .addComponent(npredikat, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nakhir, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ntugas, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nuts, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nuas, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nauas))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nauts))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(natugas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(btnSimpan)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(natugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nauts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nauas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(nuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(npredikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nhuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
            if(nama.getText().trim().isEmpty() || nim.getText().trim().isEmpty() || ntugas.getText().trim().isEmpty()|| nuts.getText().trim().isEmpty() || nuas.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Maaf Data Harus Lengkap");
            }else{
                tabel.addRow(new Object[]
                {nama.getText(),nim.getText(),ntugas.getText(),nuts.getText(),nuas.getText(),nakhir.getText(),npredikat.getText(),nhuruf.getText()});
                table.setModel(tabel);
                nama.setText("");
                nim.setText("");
                ntugas.setText("");
                nuts.setText("");
                nuas.setText("");
                natugas.setText("");
                nauts.setText("");
                nauas.setText("");
                nakhir.setText("");
                npredikat.setText("");
                nhuruf.setText("");
                JOptionPane.showMessageDialog(null,"Data Berhasil Ditambah");
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void ntugasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ntugasFocusLost
        String nntugas = ntugas.getText();
        try{
            tugas = Double.parseDouble(nntugas);
            ptugas = 0.2 * tugas;
            natugas.setText(""+ptugas);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Maaf Data Anda Tidak Valid");
        }
    }//GEN-LAST:event_ntugasFocusLost

    private void nutsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nutsFocusLost
       try{
            String nnuts = nuts.getText();
            uts = Double.parseDouble(nnuts);
            puts = 0.35 * uts;
            nauts.setText(""+puts);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Maaf Data Anda Tidak Valid");
        }
    }//GEN-LAST:event_nutsFocusLost

    private void nuasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nuasFocusLost
        try{
            String nnuas = nuas.getText();
            uas = Double.parseDouble(nnuas);
            puas = 0.45 * uas;
            nauas.setText(""+puas);
            akhir = ptugas + puts + puas;
            nakhir.setText(""+akhir);
            nhuruf.setText(""+getNilHuruf());
            npredikat.setText(""+getPredikat());
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Maaf Data Anda Tidak Valid");
        }
    }//GEN-LAST:event_nuasFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nakhir;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField natugas;
    private javax.swing.JTextField nauas;
    private javax.swing.JTextField nauts;
    private javax.swing.JTextField nhuruf;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField npredikat;
    private javax.swing.JTextField ntugas;
    private javax.swing.JTextField nuas;
    private javax.swing.JTextField nuts;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    int baris = 0;
    static Object kolom[] = {"Nama","NIM", "Tugas", "UTS","UAS","Nilai Akhir","Predikat","Nilai Huruf"};
    DefaultTableModel tabel = new DefaultTableModel(kolom,baris);
}
