/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gusaja.praktikum_13;

import java.sql.Statement;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muhba
 */
public class LapBot extends javax.swing.JFrame {

    Connection Con; 
    ResultSet RsJual; 
    Statement stm; 
    String tgl1,tgl2; 
    private Object[][] dataTable = null; 
    private String[] header = {"No Jual","Tanggal","Nama Konsumen","Kode Barang",
        "Nama Barang","Harga Satuan","Jumlah","Total"}; 
    DefaultTableModel tableModel = new DefaultTableModel( 
    new Object [][] {},header);
    /**
     * Creates new form ExportExcel
     */
    public LapBot() {
        initComponents();
        java.text.SimpleDateFormat sdf = new 
        java.text.SimpleDateFormat("yyyy-MM-dd"); 
        dateChooserCombo1.setDateFormat(sdf); 
        dateChooserCombo2.setDateFormat(sdf); 
        open_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Jual", "Tanggal", "Nama Konsumen", "Kode Barang", "Nama Barang", "Harga Satuan", "Jumlah ", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tgl");

        jLabel2.setText("S/d");

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Export Excel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        baca_data(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{ 
        ExportExcel ex=new ExportExcel(jTable1, new 
       File("DataPenjualan.xls")); 
        //exportToExcel(tblBrg, new File("DataBarang.xls")); 
        JOptionPane.showMessageDialog(null, "Sukses Export data ....."); 
        }catch(Exception e) 
        {JOptionPane.showMessageDialog(null, e); 

        } 
        } 
        /** 
        * @param args the command line arguments 
        */ 
        public static void main(String args[]) { 
        /* Set the Nimbus look and feel */ 
        //<editor-fold defaultstate="collapsed" desc=" Look and 
       //feel setting code (optional) "> 
        /* If Nimbus (introduced in Java SE 6) is not available, 
       stay with the default look and feel. 
        * For details see 
       http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/p
       laf.html 
        */ 
        try { 
        for (javax.swing.UIManager.LookAndFeelInfo info : 
       javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) { 

       javax.swing.UIManager.setLookAndFeel(info.getClassName()); 
        break; 
        } 
        } 
        } catch (ClassNotFoundException ex) { 

       java.util.logging.Logger.getLogger(LapBot.class.getName())
       .log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (InstantiationException ex) { 

       java.util.logging.Logger.getLogger(LapBot.class.getName())
       .log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (IllegalAccessException ex) { 

       java.util.logging.Logger.getLogger(LapBot.class.getName())
       .log(java.util.logging.Level.SEVERE, null, ex); 
        } catch (javax.swing.UnsupportedLookAndFeelException ex) 
       { 

       java.util.logging.Logger.getLogger(LapBot.class.getName())
       .log(java.util.logging.Level.SEVERE, null, ex); 
        } 
        //</editor-fold> 
        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() { 
        public void run() { 
        new LapBot().setVisible(true); 
        } 
        }); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void open_db() 
{ 
    try{ 
        // KoneksiMysql kon= new KoneksiMysql("penjualan"); 
        KoneksiMysql kon = new KoneksiMysql 
       ("localhost","root","","penjualan"); 
        Con = kon.getConnection(); 
        //System.out.println("Berhasil "); 
        }catch (Exception e) { 
        System.out.println("Error : "+e); 
    } 
} 
 private void format_tanggal() 
{ 
    String DATE_FORMAT = "yyyy-MM-dd"; 
    //String DATE_FORMAT = "dd-MM-yyyy"; //Refer Java DOCS for formats
    java.text.SimpleDateFormat sdf = new 
    java.text.SimpleDateFormat(DATE_FORMAT); 
    Calendar c1 = Calendar.getInstance(); 
    int year=c1.get(Calendar.YEAR); 
    int month=c1.get(Calendar.MONTH)+1; 
    int day=c1.get(Calendar.DAY_OF_MONTH); 
    //tgl1=sdf.format(txtTgl.getValue()); 
    tgl1=dateChooserCombo1.getText(); 
    tgl2=dateChooserCombo2.getText(); 
    //tgl2=Integer.toString(year)+"-"+Integer.toString(month)+"-"+Integer.toString(day); 
    System.out.println("Tanggal : " + tgl1); 
    System.out.println("Tanggal2 : " + tgl2); 
   }
 private void baca_data() 
{ 
    try{ 
        tgl1=dateChooserCombo1.getText(); 
        tgl2=dateChooserCombo2.getText(); 
        stm = (Statement) Con.createStatement(); 
        RsJual = stm.executeQuery("select * from v_penjualan where date(tgl_jual)>=" + "date('"+ tgl1+"') and date(tgl_jual)<=" + "date('" +tgl2+ "') order by tgl_jual desc"); 

        ResultSetMetaData meta = RsJual.getMetaData(); 

        int col = meta.getColumnCount(); 
        int baris = 0; 
        while(RsJual.next()) { 
        baris = RsJual.getRow(); 
    } 
 //   CustomFormat cf=new CustomFormat(); 
    dataTable = new Object[baris][col]; 
    int x = 0; 
    RsJual.beforeFirst(); 
    while(RsJual.next()) { 
    dataTable[x][0] = RsJual.getString("no_jual"); 
    dataTable[x][1] = RsJual.getDate("tgl_jual"); 
    dataTable[x][2] = RsJual.getString("nm_kons"); 
    dataTable[x][3] = RsJual.getString("kd_brg"); 
    dataTable[x][4] = RsJual.getString("nm_brg"); 
    dataTable[x][5] = 
   // cf.customFormat("###,###.##",RsJual.getDouble("harga_jual")); 
    dataTable[x][6] = RsJual.getInt("jml_jual"); 
    dataTable[x][7] = RsJual.getDouble("totjual"); 
    x++; 
    } 
    jTable1.setModel(new 
   DefaultTableModel(dataTable,header)); 
    //aturTabel(); 
    } 
    catch(SQLException e) 
    { 
    JOptionPane.showMessageDialog(null, e); 
    } 
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
